# Generated by Django 3.2.18 on 2026-08-28 10:27
# Manually reordered so existing content is copied into the new django-parler
# translation tables (as the 'en' translation) before the old columns are removed.

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models

from memorymap_toolkit.migration_utils import AlterModelBases


DEFAULT_LANGUAGE = 'en'

# (translation model name, old db table, [field names to copy])
# NOTE: by the time this data copy runs, the old fields have already been
# removed from the *migration state* (so django-parler's TranslatedFields
# proxy can be attached without a name clash), but the underlying database
# columns still physically exist (their removal is deferred to the end of
# this migration). So the old values must be read with raw SQL rather than
# through the ORM.
TRANSLATED_MODELS = [
    ('ThemeTranslation', 'mmt_map_theme', ['name']),
    ('PolygonTranslation', 'mmt_map_polygon', ['name', 'description']),
    ('PointTranslation', 'mmt_map_point', ['name', 'description']),
    ('MultiPointTranslation', 'mmt_map_multipoint', ['name', 'description']),
    ('MapLayerTranslation', 'mmt_map_maplayer', ['name']),
    ('LineTranslation', 'mmt_map_line', ['name', 'description']),
    ('ImageTranslation', 'mmt_map_image', ['description']),
    ('DocumentTranslation', 'mmt_map_document', ['title', 'body']),
]


def copy_content_to_translations(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for translation_model_name, table_name, fields in TRANSLATED_MODELS:
            TranslationModel = apps.get_model('mmt_map', translation_model_name)
            columns = ', '.join(['id'] + fields)
            cursor.execute(f'SELECT {columns} FROM {table_name}')
            rows = cursor.fetchall()
            translations = [
                TranslationModel(
                    master_id=row[0],
                    language_code=DEFAULT_LANGUAGE,
                    **dict(zip(fields, row[1:]))
                )
                for row in rows
            ]
            TranslationModel.objects.bulk_create(translations)


def noop(apps, schema_editor):
    pass


OLD_FIELD_REMOVALS = [
    migrations.RemoveField(model_name='document', name='body'),
    migrations.RemoveField(model_name='document', name='title'),
    migrations.RemoveField(model_name='image', name='description'),
    migrations.RemoveField(model_name='line', name='description'),
    migrations.RemoveField(model_name='line', name='name'),
    migrations.RemoveField(model_name='maplayer', name='name'),
    migrations.RemoveField(model_name='multipoint', name='description'),
    migrations.RemoveField(model_name='multipoint', name='name'),
    migrations.RemoveField(model_name='point', name='description'),
    migrations.RemoveField(model_name='point', name='name'),
    migrations.RemoveField(model_name='polygon', name='description'),
    migrations.RemoveField(model_name='polygon', name='name'),
    migrations.RemoveField(model_name='theme', name='name'),
]

# The actual DB columns behind OLD_FIELD_REMOVALS, dropped via raw SQL once the
# data copy has run. (Using RemoveField again here would fail: by this point
# the fields have already been removed from migration *state*, and
# RemoveField.database_forwards() needs the field to still be present in the
# state it's given in order to compute the column to drop.)
DROP_OLD_COLUMNS_SQL = [
    'ALTER TABLE mmt_map_document DROP COLUMN body;',
    'ALTER TABLE mmt_map_document DROP COLUMN title;',
    'ALTER TABLE mmt_map_image DROP COLUMN description;',
    'ALTER TABLE mmt_map_line DROP COLUMN description;',
    'ALTER TABLE mmt_map_line DROP COLUMN name;',
    'ALTER TABLE mmt_map_maplayer DROP COLUMN name;',
    'ALTER TABLE mmt_map_multipoint DROP COLUMN description;',
    'ALTER TABLE mmt_map_multipoint DROP COLUMN name;',
    'ALTER TABLE mmt_map_point DROP COLUMN description;',
    'ALTER TABLE mmt_map_point DROP COLUMN name;',
    'ALTER TABLE mmt_map_polygon DROP COLUMN description;',
    'ALTER TABLE mmt_map_polygon DROP COLUMN name;',
    'ALTER TABLE mmt_map_theme DROP COLUMN name;',
]


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_map', '0043_auto_20240926_1206'),
    ]

    operations = [
        AlterModelBases(name='Theme', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Polygon', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Point', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='MultiPoint', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='MapLayer', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Line', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Image', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Document', bases=(parler.models.TranslatableModel,)),
        migrations.SeparateDatabaseAndState(
            state_operations=OLD_FIELD_REMOVALS,
            database_operations=[],
        ),
        migrations.CreateModel(
            name='ThemeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.theme')),
            ],
            options={
                'verbose_name': 'theme Translation',
                'db_table': 'mmt_map_theme_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PolygonTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.polygon')),
            ],
            options={
                'verbose_name': 'polygon Translation',
                'db_table': 'mmt_map_polygon_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PointTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.point')),
            ],
            options={
                'verbose_name': 'point Translation',
                'db_table': 'mmt_map_point_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MultiPointTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.multipoint')),
            ],
            options={
                'verbose_name': 'multi point Translation',
                'db_table': 'mmt_map_multipoint_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MapLayerTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.maplayer')),
            ],
            options={
                'verbose_name': 'map layer Translation',
                'db_table': 'mmt_map_maplayer_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LineTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.line')),
            ],
            options={
                'verbose_name': 'line Translation',
                'db_table': 'mmt_map_line_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.image')),
            ],
            options={
                'verbose_name': 'image Translation',
                'db_table': 'mmt_map_image_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=128)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_map.document')),
            ],
            options={
                'verbose_name': 'document Translation',
                'db_table': 'mmt_map_document_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(copy_content_to_translations, noop),
        migrations.RunSQL(
            sql=DROP_OLD_COLUMNS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
