# Generated by Django 3.2.18 on 2026-04-25 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_name', models.CharField(max_length=100)),
                ('alternate_names', models.TextField(blank=True)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('wikidata_id', models.CharField(blank=True, max_length=30, null=True)),
                ('geonames_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('previous_given_name', models.CharField(blank=True, max_length=100)),
                ('previous_family_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_born_here', to='mmt_motm.locationpoint')),
                ('death_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_died_here', to='mmt_motm.locationpoint')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('person_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='mmt_motm.person')),
                ('person_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='mmt_motm.person')),
                ('urls', models.ManyToManyField(blank=True, related_name='relationships', to='mmt_motm.URL')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='persons', to='mmt_motm.URL'),
        ),
        migrations.CreateModel(
            name='LocationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('wikidata_id', models.CharField(blank=True, max_length=30, null=True)),
                ('geonames_id', models.CharField(blank=True, max_length=20, null=True)),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subregions', to='mmt_motm.locationregion')),
                ('urls', models.ManyToManyField(blank=True, related_name='regions', to='mmt_motm.URL')),
            ],
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='mmt_motm.locationregion'),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='points', to='mmt_motm.URL'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_id', models.CharField(max_length=100, unique=True)),
                ('recording_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('interviewee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_received', to='mmt_motm.person')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to='mmt_motm.person')),
                ('urls', models.ManyToManyField(blank=True, related_name='interviews', to='mmt_motm.URL')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('end_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_ended', to='mmt_motm.locationpoint')),
                ('persons', models.ManyToManyField(blank=True, related_name='events', to='mmt_motm.Person')),
                ('start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_started', to='mmt_motm.locationpoint')),
                ('urls', models.ManyToManyField(blank=True, related_name='events', to='mmt_motm.URL')),
            ],
        ),
    ]
