# Generated by Django 3.2.18 on 2026-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
