# Generated by Django 3.2.18 on 2026-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0002_alter_person_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
