# Generated by Django 3.2.18 on 2026-05-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0004_auto_20260515_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('timecode', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('event_confidence', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('concepts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='mmt_motm.concept')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='mmt_motm.event')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_from', to='mmt_motm.interview')),
                ('people_mentioned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions_mentioning', to='mmt_motm.person')),
            ],
        ),
    ]
