# Generated by Django 3.2.18 on 2026-05-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0006_extraction_concepts_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='relates_to_event',
                to='mmt_motm.event',
            ),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='people_mentioned',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='relates_to_person',
                to='mmt_motm.person',
            ),
        ),
    ]
