# Generated by Django 3.2.18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0007_auto_20260528_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Timespan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('start', 'end')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='timespan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mmt_motm.timespan'),
        ),
        migrations.AddField(
            model_name='person',
            name='lifespan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='mmt_motm.timespan'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='timespan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='mmt_motm.timespan'),
        ),
    ]
