# Generated by Django 3.2.18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0008_timespan_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
