# Generated by Django 3.2.18 on 2026-08-28 10:27
# Manually reordered so existing content is copied into the new django-parler
# translation tables (as the 'en' translation) before the old columns are removed.

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models

from memorymap_toolkit.migration_utils import AlterModelBases


DEFAULT_LANGUAGE = 'en'

# (translation model name, old db table, [field names to copy])
# NOTE: by the time this data copy runs, the old fields have already been
# removed from the *migration state* (so django-parler's TranslatedFields
# proxy can be attached without a name clash), but the underlying database
# columns still physically exist (their removal is deferred to the end of
# this migration). So the old values must be read with raw SQL rather than
# through the ORM.
TRANSLATED_MODELS = [
    ('RelationshipTypeTranslation', 'mmt_motm_relationshiptype', ['name']),
    ('PersonTranslation', 'mmt_motm_person', ['description']),
    ('LocationRegionTranslation', 'mmt_motm_locationregion', ['description']),
    ('LocationPointTranslation', 'mmt_motm_locationpoint', ['description']),
    ('InterviewTranslation', 'mmt_motm_interview', ['description']),
    ('ExtractionTranslation', 'mmt_motm_extraction', ['notes']),
    ('EventTranslation', 'mmt_motm_event', ['description']),
    ('ConceptTranslation', 'mmt_motm_concept', ['label']),
]


def copy_content_to_translations(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for translation_model_name, table_name, fields in TRANSLATED_MODELS:
            TranslationModel = apps.get_model('mmt_motm', translation_model_name)
            columns = ', '.join(['id'] + fields)
            cursor.execute(f'SELECT {columns} FROM {table_name}')
            rows = cursor.fetchall()
            translations = [
                TranslationModel(
                    master_id=row[0],
                    language_code=DEFAULT_LANGUAGE,
                    **dict(zip(fields, row[1:]))
                )
                for row in rows
            ]
            TranslationModel.objects.bulk_create(translations)


def noop(apps, schema_editor):
    pass


OLD_FIELD_REMOVALS = [
    migrations.RemoveField(model_name='concept', name='label'),
    migrations.RemoveField(model_name='event', name='description'),
    migrations.RemoveField(model_name='extraction', name='notes'),
    migrations.RemoveField(model_name='interview', name='description'),
    migrations.RemoveField(model_name='locationpoint', name='description'),
    migrations.RemoveField(model_name='locationregion', name='description'),
    migrations.RemoveField(model_name='person', name='description'),
    migrations.RemoveField(model_name='relationshiptype', name='name'),
]

# The actual DB columns behind OLD_FIELD_REMOVALS, dropped via raw SQL once the
# data copy has run. (Using RemoveField again here would fail: by this point
# the fields have already been removed from migration *state*, and
# RemoveField.database_forwards() needs the field to still be present in the
# state it's given in order to compute the column to drop.)
DROP_OLD_COLUMNS_SQL = [
    'ALTER TABLE mmt_motm_concept DROP COLUMN label;',
    'ALTER TABLE mmt_motm_event DROP COLUMN description;',
    'ALTER TABLE mmt_motm_extraction DROP COLUMN notes;',
    'ALTER TABLE mmt_motm_interview DROP COLUMN description;',
    'ALTER TABLE mmt_motm_locationpoint DROP COLUMN description;',
    'ALTER TABLE mmt_motm_locationregion DROP COLUMN description;',
    'ALTER TABLE mmt_motm_person DROP COLUMN description;',
    'ALTER TABLE mmt_motm_relationshiptype DROP COLUMN name;',
]


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0016_add_estimated_certainty'),
    ]

    operations = [
        AlterModelBases(name='RelationshipType', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Person', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='LocationRegion', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='LocationPoint', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Interview', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Extraction', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Event', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Concept', bases=(parler.models.TranslatableModel,)),
        migrations.SeparateDatabaseAndState(
            state_operations=OLD_FIELD_REMOVALS,
            database_operations=[],
        ),
        migrations.CreateModel(
            name='RelationshipTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.relationshiptype')),
            ],
            options={
                'verbose_name': 'relationship type Translation',
                'db_table': 'mmt_motm_relationshiptype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.person')),
            ],
            options={
                'verbose_name': 'Person Translation',
                'db_table': 'mmt_motm_person_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LocationRegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.locationregion')),
            ],
            options={
                'verbose_name': 'Region Translation',
                'db_table': 'mmt_motm_locationregion_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LocationPointTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.locationpoint')),
            ],
            options={
                'verbose_name': 'Location Translation',
                'db_table': 'mmt_motm_locationpoint_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InterviewTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.interview')),
            ],
            options={
                'verbose_name': 'interview Translation',
                'db_table': 'mmt_motm_interview_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExtractionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('notes', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.extraction')),
            ],
            options={
                'verbose_name': 'extraction Translation',
                'db_table': 'mmt_motm_extraction_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.event')),
            ],
            options={
                'verbose_name': 'event Translation',
                'db_table': 'mmt_motm_event_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConceptTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_motm.concept')),
            ],
            options={
                'verbose_name': 'concept Translation',
                'db_table': 'mmt_motm_concept_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(copy_content_to_translations, noop),
        migrations.RunSQL(
            sql=DROP_OLD_COLUMNS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
