# Generated by Django 3.2.18 on 2026-08-28 10:27
# Manually reordered so existing content is copied into the new django-parler
# translation tables (as the 'en' translation) before the old columns are removed.

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models

from memorymap_toolkit.migration_utils import AlterModelBases


DEFAULT_LANGUAGE = 'en'

# (translation model name, old db table, [field names to copy])
# NOTE: by the time this data copy runs, the old fields have already been
# removed from the *migration state* (so django-parler's TranslatedFields
# proxy can be attached without a name clash), but the underlying database
# columns still physically exist (their removal is deferred to the end of
# this migration). So the old values must be read with raw SQL rather than
# through the ORM.
TRANSLATED_MODELS = [
    ('SectionTranslation', 'mmt_pages_section', ['title', 'body']),
    ('PageTranslation', 'mmt_pages_page', ['title', 'body']),
]


def copy_content_to_translations(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for translation_model_name, table_name, fields in TRANSLATED_MODELS:
            TranslationModel = apps.get_model('mmt_pages', translation_model_name)
            columns = ', '.join(['id'] + fields)
            cursor.execute(f'SELECT {columns} FROM {table_name}')
            rows = cursor.fetchall()
            translations = [
                TranslationModel(
                    master_id=row[0],
                    language_code=DEFAULT_LANGUAGE,
                    **dict(zip(fields, row[1:]))
                )
                for row in rows
            ]
            TranslationModel.objects.bulk_create(translations)


def noop(apps, schema_editor):
    pass


OLD_FIELD_REMOVALS = [
    migrations.RemoveField(model_name='page', name='body'),
    migrations.RemoveField(model_name='page', name='title'),
    migrations.RemoveField(model_name='section', name='body'),
    migrations.RemoveField(model_name='section', name='title'),
]

# The actual DB columns behind OLD_FIELD_REMOVALS, dropped via raw SQL once the
# data copy has run. (Using RemoveField again here would fail: by this point
# the fields have already been removed from migration *state*, and
# RemoveField.database_forwards() needs the field to still be present in the
# state it's given in order to compute the column to drop.)
DROP_OLD_COLUMNS_SQL = [
    'ALTER TABLE mmt_pages_page DROP COLUMN body;',
    'ALTER TABLE mmt_pages_page DROP COLUMN title;',
    'ALTER TABLE mmt_pages_section DROP COLUMN body;',
    'ALTER TABLE mmt_pages_section DROP COLUMN title;',
]


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_pages', '0009_alter_section_slug'),
    ]

    operations = [
        AlterModelBases(name='Section', bases=(parler.models.TranslatableModel,)),
        AlterModelBases(name='Page', bases=(parler.models.TranslatableModel,)),
        migrations.SeparateDatabaseAndState(
            state_operations=OLD_FIELD_REMOVALS,
            database_operations=[],
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=140)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_pages.section')),
            ],
            options={
                'verbose_name': 'section Translation',
                'db_table': 'mmt_pages_section_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=140)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mmt_pages.page')),
            ],
            options={
                'verbose_name': 'page Translation',
                'db_table': 'mmt_pages_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(copy_content_to_translations, noop),
        migrations.RunSQL(
            sql=DROP_OLD_COLUMNS_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
